<?php

function ether_forms_countries()
{
	return array
	(
		'af' => ether::langr('Afghanistan'),
		'al' => ether::langr('Albania'),
		'dz' => ether::langr('Algeria'),
		'as' => ether::langr('American Samoa'),
		'ad' => ether::langr('Andorra'),
		'ao' => ether::langr('Angola'),
		'ag' => ether::langr('Antigua and Barbuda'),
		'ar' => ether::langr('Argentina'),
		'am' => ether::langr('Armenia'),
		'au' => ether::langr('Australia'),
		'at' => ether::langr('Austria'),
		'az' => ether::langr('Azerbaijan'),
		'bs' => ether::langr('Bahamas'),
		'bh' => ether::langr('Bahrain'),
		'bd' => ether::langr('Bangladesh'),
		'bb' => ether::langr('Barbados'),
		'by' => ether::langr('Belarus'),
		'be' => ether::langr('Belgium'),
		'bz' => ether::langr('Belize'),
		'bj' => ether::langr('Benin'),
		'bm' => ether::langr('Bermuda'),
		'bt' => ether::langr('Bhutan'),
		'bo' => ether::langr('Bolivia'),
		'ba' => ether::langr('Bosnia and Herzegovina'),
		'bw' => ether::langr('Botswana'),
		'br' => ether::langr('Brazil'),
		'bn' => ether::langr('Brunei'),
		'bg' => ether::langr('Bulgaria'),
		'bf' => ether::langr('Burkina Faso'),
		'bi' => ether::langr('Burundi'),
		'kh' => ether::langr('Cambodia'),
		'cm' => ether::langr('Cameroon'),
		'ca' => ether::langr('Canada'),
		'cv' => ether::langr('Cape Verde'),
		'cf' => ether::langr('Central African Republic'),
		'td' => ether::langr('Chad'),
		'cl' => ether::langr('Chile'),
		'cn' => ether::langr('China'),
		'co' => ether::langr('Colombia'),
		'km' => ether::langr('Comoros'),
		'cg' => ether::langr('Congo'),
		'cr' => ether::langr('Costa Rica'),
		'ci' => ether::langr('C&ocirc;te d\'Ivoire'),
		'hr' => ether::langr('Croatia'),
		'cu' => ether::langr('Cuba'),
		'cy' => ether::langr('Cyprus'),
		'cz' => ether::langr('Czech Republic'),
		'dk' => ether::langr('Denmark'),
		'dj' => ether::langr('Djibouti'),
		'dm' => ether::langr('Dominica'),
		'do' => ether::langr('Dominican Republic'),
		'tl' => ether::langr('East Timor'),
		'ec' => ether::langr('Ecuador'),
		'eg' => ether::langr('Egypt'),
		'sv' => ether::langr('El Salvador'),
		'gq' => ether::langr('Equatorial Guinea'),
		'er' => ether::langr('Eritrea'),
		'ee' => ether::langr('Estonia'),
		'et' => ether::langr('Ethiopia'),
		'fj' => ether::langr('Fiji'),
		'fi' => ether::langr('Finland'),
		'fr' => ether::langr('France'),
		'ga' => ether::langr('Gabon'),
		'gm' => ether::langr('Gambia'),
		'ge' => ether::langr('Georgia'),
		'de' => ether::langr('Germany'),
		'gh' => ether::langr('Ghana'),
		'gr' => ether::langr('Greece'),
		'gl' => ether::langr('Greenland'),
		'gd' => ether::langr('Grenada'),
		'gu' => ether::langr('Guam'),
		'gt' => ether::langr('Guatemala'),
		'gn' => ether::langr('Guinea'),
		'gw' => ether::langr('Guinea-Bissau'),
		'gy' => ether::langr('Guyana'),
		'ht' => ether::langr('Haiti'),
		'hn' => ether::langr('Honduras'),
		'hk' => ether::langr('Hong Kong'),
		'hu' => ether::langr('Hungary'),
		'is' => ether::langr('Iceland'),
		'in' => ether::langr('India'),
		'id' => ether::langr('Indonesia'),
		'ir' => ether::langr('Iran'),
		'iq' => ether::langr('Iraq'),
		'ie' => ether::langr('Ireland'),
		'il' => ether::langr('Israel'),
		'it' => ether::langr('Italy'),
		'jm' => ether::langr('Jamaica'),
		'jp' => ether::langr('Japan'),
		'jo' => ether::langr('Jordan'),
		'kz' => ether::langr('Kazakhstan'),
		'ke' => ether::langr('Kenya'),
		'ki' => ether::langr('Kiribati'),
		'kp' => ether::langr('North Korea'),
		'kr' => ether::langr('South Korea'),
		'kw' => ether::langr('Kuwait'),
		'kg' => ether::langr('Kyrgyzstan'),
		'la' => ether::langr('Laos'),
		'lv' => ether::langr('Latvia'),
		'lb' => ether::langr('Lebanon'),
		'ls' => ether::langr('Lesotho'),
		'lr' => ether::langr('Liberia'),
		'ly' => ether::langr('Libya'),
		'li' => ether::langr('Liechtenstein'),
		'lt' => ether::langr('Lithuania'),
		'lu' => ether::langr('Luxembourg'),
		'mk' => ether::langr('Macedonia'),
		'mg' => ether::langr('Madagascar'),
		'mw' => ether::langr('Malawi'),
		'my' => ether::langr('Malaysia'),
		'mv' => ether::langr('Maldives'),
		'ml' => ether::langr('Mali'),
		'mt' => ether::langr('Malta'),
		'mh' => ether::langr('Marshall Islands'),
		'mr' => ether::langr('Mauritania'),
		'mu' => ether::langr('Mauritius'),
		'mx' => ether::langr('Mexico'),
		'fm' => ether::langr('Micronesia'),
		'md' => ether::langr('Moldova'),
		'mc' => ether::langr('Monaco'),
		'mn' => ether::langr('Mongolia'),
		'me' => ether::langr('Montenegro'),
		'ma' => ether::langr('Morocco'),
		'mz' => ether::langr('Mozambique'),
		'mm' => ether::langr('Myanmar'),
		'na' => ether::langr('Namibia'),
		'nr' => ether::langr('Nauru'),
		'np' => ether::langr('Nepal'),
		'nl' => ether::langr('Netherlands'),
		'nz' => ether::langr('New Zealand'),
		'ni' => ether::langr('Nicaragua'),
		'ne' => ether::langr('Niger'),
		'ng' => ether::langr('Nigeria'),
		'no' => ether::langr('Norway'),
		'mp' => ether::langr('Northern Mariana Islands'),
		'om' => ether::langr('Oman'),
		'pk' => ether::langr('Pakistan'),
		'pw' => ether::langr('Palau'),
		'ps' => ether::langr('Palestine'),
		'pa' => ether::langr('Panama'),
		'pg' => ether::langr('Papua New Guinea'),
		'py' => ether::langr('Paraguay'),
		'pe' => ether::langr('Peru'),
		'ph' => ether::langr('Philippines'),
		'pl' => ether::langr('Poland'),
		'pt' => ether::langr('Portugal'),
		'pr' => ether::langr('Puerto Rico'),
		'qa' => ether::langr('Qatar'),
		'ro' => ether::langr('Romania'),
		'ru' => ether::langr('Russia'),
		'rw' => ether::langr('Rwanda'),
		'kn' => ether::langr('Saint Kitts and Nevis'),
		'lc' => ether::langr('Saint Lucia'),
		'vc' => ether::langr('Saint Vincent and the Grenadines'),
		'ws' => ether::langr('Samoa'),
		'sm' => ether::langr('San Marino'),
		'st' => ether::langr('Sao Tome and Principe'),
		'sa' => ether::langr('Saudi Arabia'),
		'sn' => ether::langr('Senegal'),
		'rs' => ether::langr('Serbia and Montenegro'),
		'sc' => ether::langr('Seychelles'),
		'sl' => ether::langr('Sierra Leone'),
		'sg' => ether::langr('Singapore'),
		'sk' => ether::langr('Slovakia'),
		'si' => ether::langr('Slovenia'),
		'sb' => ether::langr('Solomon Islands'),
		'so' => ether::langr('Somalia'),
		'za' => ether::langr('South Africa'),
		'es' => ether::langr('Spain'),
		'lk' => ether::langr('Sri Lanka'),
		'sd' => ether::langr('Sudan'),
		'sr' => ether::langr('Suriname'),
		'sz' => ether::langr('Swaziland'),
		'se' => ether::langr('Sweden'),
		'ch' => ether::langr('Switzerland'),
		'sy' => ether::langr('Syria'),
		'tw' => ether::langr('Taiwan'),
		'tj' => ether::langr('Tajikistan'),
		'tz' => ether::langr('Tanzania'),
		'th' => ether::langr('Thailand'),
		'tg' => ether::langr('Togo'),
		'to' => ether::langr('Tonga'),
		'tt' => ether::langr('Trinidad and Tobago'),
		'tn' => ether::langr('Tunisia'),
		'tr' => ether::langr('Turkey'),
		'tm' => ether::langr('Turkmenistan'),
		'tv' => ether::langr('Tuvalu'),
		'ug' => ether::langr('Uganda'),
		'ua' => ether::langr('Ukraine'),
		'ae' => ether::langr('United Arab Emirates'),
		'gb' => ether::langr('United Kingdom'),
		'us' => ether::langr('United States'),
		'uy' => ether::langr('Uruguay'),
		'uz' => ether::langr('Uzbekistan'),
		'vu' => ether::langr('Vanuatu'),
		've' => ether::langr('Venezuela'),
		'vn' => ether::langr('Vietnam'),
		'vg' => ether::langr('Virgin Islands, British'),
		'vi' => ether::langr('Virgin Islands, U.S.'),
		'ye' => ether::langr('Yemen'),
		'zm' => ether::langr('Zambia'),
		'zw' => ether::langr('Zimbabwe')
	);
}

function ether_forms_genders()
{
	return array
	(
		ether::langr('Male'),
		ether::langr('Female')
	);
}

function ether_forms_us_states()
{
	return array
	(
		ether::langr('Alabama'),
		ether::langr('Alaska'),
		ether::langr('Arizona'),
		ether::langr('Arkansas'),
		ether::langr('California'),
		ether::langr('Colorado'),
		ether::langr('Connecticut'),
		ether::langr('Delaware'),
		ether::langr('District of Columbia'),
		ether::langr('Florida'),
		ether::langr('Georgia'),
		ether::langr('Hawaii'),
		ether::langr('Idaho'),
		ether::langr('Illinois'),
		ether::langr('Indiana'),
		ether::langr('Iowa'),
		ether::langr('Kansas'),
		ether::langr('Kentucky'),
		ether::langr('Louisiana'),
		ether::langr('Maine'),
		ether::langr('Maryland'),
		ether::langr('Massachusetts'),
		ether::langr('Michigan'),
		ether::langr('Minnesota'),
		ether::langr('Mississippi'),
		ether::langr('Missouri'),
		ether::langr('Montana'),
		ether::langr('Nebraska'),
		ether::langr('Nevada'),
		ether::langr('New Hampshire'),
		ether::langr('New Jersey'),
		ether::langr('New Mexico'),
		ether::langr('New York'),
		ether::langr('North Carolina'),
		ether::langr('North Dakota'),
		ether::langr('Ohio'),
		ether::langr('Oklahoma'),
		ether::langr('Oregon'),
		ether::langr('Pennsylvania'),
		ether::langr('Rhode Island'),
		ether::langr('South Carolina'),
		ether::langr('South Dakota'),
		ether::langr('Tennessee'),
		ether::langr('Texas'),
		ether::langr('Utah'),
		ether::langr('Vermont'),
		ether::langr('Virginia'),
		ether::langr('Washington'),
		ether::langr('West Virginia'),
		ether::langr('Wisconsin'),
		ether::langr('Wyoming')
	);
}

function ether_forms_continents()
{
	return array
	(
		ether::langr('Africa'),
		ether::langr('Antarctica'),
		ether::langr('Asia'),
		ether::langr('Australia'),
		ether::langr('Europe'),
		ether::langr('North America'),
		ether::langr('South America')
	);
}

function ether_forms_days()
{
	return array
	(
		ether::langr('Sunday'),
		ether::langr('Monday'),
		ether::langr('Tuesday'),
		ether::langr('Wednesday'),
		ether::langr('Thursday'),
		ether::langr('Friday'),
		ether::langr('Saturday')
	);
}

function ether_forms_months()
{
	return array
	(
		ether::langr('January'),
		ether::langr('February'),
		ether::langr('March'),
		ether::langr('April'),
		ether::langr('May'),
		ether::langr('June'),
		ether::langr('July'),
		ether::langr('August'),
		ether::langr('September'),
		ether::langr('October'),
		ether::langr('November'),
		ether::langr('December')
	);
}

?>
